apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: b44qy5gra-python-gitops
  description: This is GitOps manifest for b44qy5gra-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=b44qy5gra-python
    backstage.io/kubernetes-id: b44qy5gra-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: b44qy5gra-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:b44qy5gra-python
